sudo: false
language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

services:
  - redis-server

matrix:
  include:
    - rust: stable
      env: RUST_VERSION=stable COMMAND=test COV=yes

    - rust: beta
      env: RUST_VERSION=beta COMMAND=test

    - rust: nightly
      env: RUST_VERSION=nightly COMMAND=test

    - rust: stable
      env: COMMAND=lint

script:
  - make $COMMAND
  - cargo check --benches

after_success:
  - [ "$COV" = "yes" ] && \
    cargo install cargo-tarpaulin && \
    cargo tarpaulin -v --ignore-tests --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
