sudo: false
language: rust
cache: cargo

matrix:
  include:
    - rust: stable
      env: RUST_VERSION=stable COMMAND=cargo test

    - rust: beta
      env: RUST_VERSION=beta COMMAND=cargo test

    - rust: nightly
      env: RUST_VERSION=nightly COMMAND=cargo test

    - rust: stable
      env: COMMAND=make lint

script:
  - $COMMAND
  - cargo check --benches

after_success:
  - cargo install cargo-tarpaulin
  - cargo tarpaulin -v --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
