sudo: false
language: rust
cache: cargo

services:
  - redis-server

matrix:
  include:
    - rust: stable
      env: RUST_VERSION=stable COMMAND=test

    - rust: beta
      env: RUST_VERSION=beta COMMAND=test

    - rust: nightly
      env: RUST_VERSION=nightly COMMAND=test

    - rust: stable
      env: COMMAND=lint

script:
  - make $COMMAND
  - cargo check --benches

after_success:
  - |
    [ "$RUST_VERSION" != "stable" ] && [ "$COMMAND" != "test" ] && exit 0
    cargo install cargo-tarpaulin && \
    cargo tarpaulin -v --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
